apiVersion: v1
kind: ConfigMap
metadata:
  name: contract-centry-config
  namespace: contract-centry
data:
  LOG_LEVEL: "INFO"
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis:6379/1"
  REDIS_URL: "redis://redis:6379/0"
  DATABASE_URL: "postgresql+asyncpg://centry:centry@postgres:5432/centry"
